---
- name: Install Phpansible development environment 
  hosts: all
  sudo: True
  vars: 
    root_folder: "/var/www"
    server_name: "phpansible.dev"
    document_root: "{{ root_folder }}/{{ server_name }}"
    nginx_folder: "/etc/nginx"
  tasks:
    - include: tasks/common.yml
    - include: tasks/nginx.yml
    - include: tasks/php.yml
  handlers:
    - include: handlers/nginx.yml
    - include: handlers/php.yml
