---
- name: PHP - Install
  apt: pkg=$item state=installed
  with_items:
    - php5
    - php5-cli
    - php5-fpm
    - php5-xdebug
- name: PHP - Disable default configuration
  command: mv /etc/php5/fpm/pool.d/www.conf /etc/php5/fpm/pool.d/www.disabled creates=/etc/php5/fpm/pool.d/www.disabled
- name: PHP - Configure FPM
  template: src=files/php5-fpm.conf dest=/etc/php5/fpm/pool.d/phpansible.conf
  notify: PHP - Restart FPM
- name: PHP - Install Composer
  shell: 
    curl -sS https://getcomposer.org/installer | /usr/bin/php && /bin/mv -f /home/vagrant/composer.phar /usr/local/bin/composer 
    creates=/usr/local/bin/composer
